engines:
  eslint:
    enabled: true
  fixme:
    enabled: true
languages:
  JavaScript: true
ratings:
  paths:
  - "source/**"
  - "tests/**"
exclude_paths:
- "index.js"
- "build/**"
- "coverage/**"
- "documentation/**"
- "node_modules/**/*"
- "specifications/**"